# На какой группе серверов
- hosts: appservers

  tasks:
    - name: install git
      # apt-get update && apt-get install redis-server
      ansible.builtin.apt: # имя модуля Ansible
        name: git
        state: present
        update_cache: yes
      become: yes
